[package]
name = "copier-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
copier-core = { path = "../copier-core" }
tokio = { workspace = true }
thiserror = { workspace = true }
