name: ci

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.81.0
      - run: cargo check --workspace
      - run: cargo test --workspace
      - run: cargo build --workspace --release
